[2025-06-22 13:02:22,998: WARNING/ForkPoolWorker-5] Traceback (most recent call last):
2025-06-22 18:32:22


[2025-06-22 13:02:22,998: WARNING/ForkPoolWorker-5]   File "/app/services/content_analyzer.py", line 115, in analyze_news_article_content
2025-06-22 18:32:22


    gemini_response_text = gemini_response_object.text if gemini_response_object and hasattr(gemini_response_object, 'text') else None
2025-06-22 18:32:22


[2025-06-22 13:02:22,998: WARNING/ForkPoolWorker-5]   File "/usr/local/lib/python3.9/site-packages/google/generativeai/types/generation_types.py", line 481, in text
2025-06-22 18:32:22


    raise ValueError(msg)
2025-06-22 18:32:22


[2025-06-22 13:02:22,998: WARNING/ForkPoolWorker-5] ValueError: Invalid operation: The `response.text` quick accessor requires the response to contain a valid `Part`, but none were returned. The candidate's [finish_reason](https://ai.google.dev/api/generate-content#finishreason) is 2.
2025-06-22 18:32:27


[2025-06-22 13:02:27,212: WARNING/ForkPoolWorker-5] [52] ImgAnalyzer: JSON parsing error for celery_dl_291c94958f9c44149b65264066f6786a_Delhi---June-22--2025_ddb63aa9_p004_crop010_f66e6c. Error: Failed to parse JSON from model response. Raw: ```json
2025-06-22 18:32:27


{